---
common_apt_cache_valid_time: 3600 # 1 hour
common_package_repositories: []
common_packages: []
common_users: []
common_groups: []

sudo_groups:
  - sudo

common_security_sysctl:
  fs.suid_dumpable: "0"
  kernel.core_uses_pid: "1"
  kernel.dmesg_restrict: "1"
  kernel.kptr_restrict: "2"
  kernel.sysrq: "0"
  net.ipv4.conf.all.log_martians: "1"
  net.ipv4.conf.all.send_redirects: "0"
  net.ipv4.conf.default.accept_source_route: "0"
  net.ipv4.conf.default.log_martians: "1"
