---
nginx_config_directory: /etc/avans-informatica-breda.nl/nginx
nginx_host_letsencrypt_email: example@example.com
digitalocean_token: ""

default_group:
  gid: 9000
  name: "rungroup"

default_user:
  uid: 9000
  name: "runuser"
  group: "{{ default_group.name }}"
  groups: [docker]

project_name: entrypoint
project_dir: /srv/app
project_docker_files:
  - "{{ project_dir }}/docker-compose.yml"
